<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Page</title>
<meta name="generator" content="WYSIWYG Web Builder 14 - http://www.wysiwygwebbuilder.com">
<link href="Untitled1.css" rel="stylesheet">
<link href="index.css" rel="stylesheet">
</head>
<body>
<picture id="wb_Picture1" style="position:absolute;left:41px;top:64px;width:176px;height:196px;z-index:0">
<img src="images/icegif-4910.gif" id="Picture1" alt="" srcset="">
</picture>
<div id="wb_Text1" style="position:absolute;left:314px;top:76px;width:402px;height:98px;z-index:1;">
<span style="color:#FFFFFF;font-family:Georgia;font-size:43px;"><strong>Welcome to </strong></span><span style="color:#FF00FF;font-family:Georgia;font-size:43px;"><strong>Angelica's</strong></span><span style="color:#FFFFFF;font-family:Georgia;font-size:43px;"><strong> Shop</strong></span></div>
<div id="wb_Text2" style="position:absolute;left:314px;top:204px;width:424px;height:70px;z-index:2;">
<span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>Grow your business today with our </strong></span><span style="color:#00FEFE;font-family:'MS Serif';font-size:32px;"><strong>SEO TOOLS</strong></span></div>
<div id="wb_Image2" style="position:absolute;left:24px;top:840px;width:842px;height:107px;z-index:3;">
<img src="images/standard-ezgif.com-effects.gif" id="Image2" alt=""></div>
<div id="wb_Text4" style="position:absolute;left:1083px;top:535px;width:417px;height:16px;z-index:4;">
<span style="color:#000000;font-family:Arial;font-size:13px;">https://www.reddit.com/user/Brilliant-War3167/</span></div>
<div id="wb_Text5" style="position:absolute;left:866px;top:551px;width:417px;height:16px;z-index:5;">
<span style="color:#000000;font-family:Arial;font-size:13px;">https://www.reddit.com/user/Brilliant-War3167/</span></div>
<div id="wb_Image1" style="position:absolute;left:876px;top:841px;width:764px;height:104px;z-index:6;">
<img src="images/standard1-ezgif.com-effects (1).gif" id="Image1" alt=""></div>
<div id="wb_Text3" style="position:absolute;left:33px;top:358px;width:1139px;height:245px;z-index:7;">
<span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>IDA PRO 9&nbsp; </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$1925</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$200</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>INSTAGRAM BOT&nbsp; </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$299</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$30</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>BULK EMAIL SENDER </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$100</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$30</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>EMAIL CHECKER </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$30</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$10</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>FACEBOOK TOKEN GENERATOR </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$49</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$10</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>DISCORD BOT CREATOR </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$149</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$30<br></strong></span></div>
<div id="wb_Text6" style="position:absolute;left:1211px;top:90px;width:429px;height:70px;z-index:8;">
<span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>E-Mail:<br>cutelittlemaggie1@gmail.com</strong></span></div>
<div id="wb_Text7" style="position:absolute;left:33px;top:587px;width:1139px;height:245px;z-index:9;">
<span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>LINKEDIN CONTACT INFO EXCTRACTOR<br>WEBSITE TRAFFIC CREATOR (+FREE PROXIES) </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$399</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$100</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>TELEGRAM CONTACT INFO SCRAPPER&nbsp; </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$50</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$10</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>GOOGLE MAPS CONTACT INFO SCRAPPER </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$1299</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$150</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>DISCORD ACCOUNT MAKER (+PROXIES) </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$300</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$20</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br>ESET ANTIVIRUS LIFETIME </strong></span><span style="background-color:#FF0000;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>- <strike>$100</strike></strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong> </strong></span><span style="background-color:#228B22;color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>$20</strong></span><span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong><br></strong></span></div>
<div id="wb_Text8" style="position:absolute;left:1083px;top:204px;width:511px;height:70px;z-index:10;">
<span style="color:#FFFFFF;font-family:'MS Serif';font-size:32px;"><strong>Send us an email to buy a program. We accept PayPal F&amp;F and ETH</strong></span></div>
<div id="wb_MediaPlayer1" style="position:absolute;left:876px;top:75px;width:99px;height:99px;z-index:11;">
<audio id="MediaPlayer1" autoplay controls loop preload="auto">
<source src="Vangelis - Sweet Solitude.mp3" type="audio/mpeg" />
<source src="Vangelis - Sweet Solitude.mp3" type="audio/mpeg" />
</audio>
</div>
</body>
</html>